### ISSUE TITLE
"None" error after installing

### ISSUE THREAD

**Issue by Eeleco** [PimDoos/onesmartcontrolha#34]
V 3.0 (release)

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.onesmartcontrol.onesmartwrapper
Source: custom_components/onesmartcontrol/onesmartwrapper.py:88
Integration: One Smart Control (documentation, issues)
First occurred: 11:21:03 (1 occurrences)
Last logged: 11:21:03

Authentication error: [Errno 104] Connection reset by peer

‐----- SECOND ERROR ------
Logger: homeassistant.config_entries
Source: config_entries.py:1034
First occurred: 11:21:03 (1 occurrences)
Last logged: 11:21:03

Config entry 'One Smart Control' for onesmartcontrol integration could not authenticate: None

------- THIRD ERROR -------

Logger: homeassistant
Source: data_entry_flow.py:362
First occurred: 11:21:03 (1 occurrences)
Last logged: 11:21:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 362, in _async_handle_step
    raise UnknownStep(
homeassistant.data_entry_flow.UnknownStep: Handler ConfigFlow doesn't support step reauth

**Comment by PimDoos** [comment]
The third error should be fixable by adding reauthentication to the config flow. I'll add these in the next version.
The first two are likely caused by the OneConnect resetting the connection before the integration completes authentication. This might be a temporary or networking issue. 
If not, I'd like to see whether the debug_devices script works properly or not.

**Comment by Eeleco** [comment]
Debug export send (the debug was without fixes applied)

Testing these changes;
- The initial error is resolved, devices are recognized again.

**New error's;**
Logger: homeassistant.config_entries
Source: config_entries.py:1111
First occurred: 14:46:10 (1 occurrences)
Last logged: 14:46:10

Config entry 'One Smart Control' for onesmartcontrol integration not ready yet: None; Retrying in background

**Second error**
Logger: homeassistant.components.sensor
Source: custom_components/onesmartcontrol/onesmartentity.py:31
Integration: Sensor (documentation, issues)
First occurred: 14:47:16 (1 occurrences)
Last logged: 14:47:16

Error while setting up onesmartcontrol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/onesmartcontrol/sensor.py", line 92, in async_setup_entry
    OneSmartSensor(
  File "/config/custom_components/onesmartcontrol/sensor.py", line 127, in __init__
    super().__init__(hass, config_entry, wrapper, update_topic, source, device_id, name, suffix, icon)
  File "/config/custom_components/onesmartcontrol/onesmartentity.py", line 31, in __init__
    self._room = rooms[self._device[OneSmartFieldName.ROOM]]
KeyError: ''

**Third error**
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.onesmartcontrol.onesmartwrapper
Source: custom_components/onesmartcontrol/onesmartwrapper.py:478
Integration: One Smart Control (documentation, issues)
First occurred: 14:48:14 (4 occurrences)
Last logged: 14:49:17

Command on socket poll timed out after 60 seconds: apparatus

**Fourth error**
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.onesmartcontrol.onesmartwrapper
Source: custom_components/onesmartcontrol/onesmartwrapper.py:247
Integration: One Smart Control (documentation, issues)
First occurred: 14:48:14 (4 occurrences)
Last logged: 14:49:17

Could not update ['operating_mode', 'room_temperature_zone1', 'hc_thermostat_target_temperature_zone1', 'system_onoff'] for 'HEATPUMP': Client read timed out
Could not update ['fault_code', 'inverter_temperature', 'phase_3_output_power', 'phase_3_output_current'] for 'PV INVERTER': Client read timed out

**Comment by Eeleco** [comment]
**Fourth error update**

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.onesmartcontrol.onesmartwrapper
Source: custom_components/onesmartcontrol/onesmartwrapper.py:247
Integration: One Smart Control (documentation, issues)
First occurred: 14:48:14 (30 occurrences)
Last logged: 15:09:52

Could not update ['co2_level_first_floor', 'co2_level_ground_floor', 'exit_air_temperature', 'inlet_air_temperature'] for 'COMFOAIR': Client read timed out
Could not update ['phase_1_output_power', 'phase_1_output_current', 'phase_1_output_voltage', 'grid_frequency'] for 'PV INVERTER': Client read timed out
Could not update ['outside_air_temperature', 'outlet_ventilator_rpm', 'inlet_ventilator_rpm', 'outlet_air_percentage'] for 'COMFOAIR': Client read timed out
Could not update ['apiversion'] for 'HUE BRIDGE': Client read timed out
Could not update ['apiversion'] for 'HUE BRIDGE': Server responded with {'error': 3, 'description': 'timeout'}

**Comment by Eeleco** [comment]
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.onesmartcontrol.onesmartwrapper
Source: custom_components/onesmartcontrol/onesmartwrapper.py:478
Integration: One Smart Control (documentation, issues)
First occurred: 15:17:33 (6 occurrences)
Last logged: 15:33:01

Command on socket poll timed out after 60 seconds: apparatus

**Comment by PimDoos** [comment]
As discussed seperately, this appears to be fixed with a reboot of the OneEnergy
