### ISSUE TITLE
Unknown error occurred while doing setup

### ISSUE THREAD

**Issue by rept** [PimDoos/onesmartcontrolha#38]
First of all, thanks for the great work. This convinced me to actually install HomeAssitant in the first place.

While doing the setup I enter the credentials and IP address and then get a "Unknown error occurred"

I'm running version 0.3.1

While checking the logs I see 2 errors a second apart:

```
Logger: custom_components.onesmartcontrol.onesmartwrapper
Source: custom_components/onesmartcontrol/onesmartwrapper.py:88
Integration: onesmartcontrol ([documentation](https://github.com/PimDoos/onesmartcontrolha), [issues](https://github.com/PimDoos/onesmartcontrolha/issues))
First occurred: 00:30:22 (1 occurrences)
Last logged: 00:30:22

Error while discovering entities for device ONEDOOR: <OneSmartFieldName.ATTRIBUTES: 'attributes'>
```

And after this:

```Logger: aiohttp.server
Source: custom_components/onesmartcontrol/config_flow.py:88
Integration: onesmartcontrol ([documentation](https://github.com/PimDoos/onesmartcontrolha), [issues](https://github.com/PimDoos/onesmartcontrolha/issues))
First occurred: 00:30:23 (1 occurrences)
Last logged: 00:30:23

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/onesmartcontrol/config_flow.py", line 88, in async_step_user
    return self.async_create_entry(title=info["title"], data=user_input)
TypeError: ConfigFlow.async_create_entry() got an unexpected keyword argument 'title'
```

**Comment by PimDoos** [comment]
Fixed in [v0.3.2](https://github.com/PimDoos/onesmartcontrolha/releases/tag/v0.3.2)
